### ISSUE TITLE
Friends Page basic frontend

### ISSUE THREAD

**Issue by benjamingetches** [benjamingetches/UnderLeaf#15]
Basic set up for front end, without connections

**Comment by harrison-66** [comment]
I'm working on sharing notes-- so I need to set up a super simple friends system. Its going to be basic af- needs a overhaul ASAP, as right now friend requests are one-way-- ie as a user, i just type someones username and then we are now friends.

**Comment by harrison-66** [comment]
added remove friend, as well as changed up front end to allow for new friend request/accept feature rather than the above

**Comment by harrison-66** [comment]
Probably still needs 
- UI to be a bit cleaner
- better integration with the notes page/editor (who shared/owns the note, share requests?, idk)
